### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by TheMolkaPL** [bartzzdev/VarGuilds#1]
Mógłbyś używać [Apache Maven](https://maven.apache.org/) do budowania swojego projektu. Ułatwia on zarządzanie dependencies i kompilacje pliku `JAR`.

**Comment by MrGregorix** [comment]
Mógłbyś także np. PRZESTAĆ ROBIĆ TE GILDIE BO SĄ OKROPNE

**Comment by TheMolkaPL** [comment]
> Mógłbyś także np. PRZESTAĆ ROBIĆ TE GILDIE BO SĄ OKROPNE

To już jak kto uważa ;) Osobiście znudziły mnie tego typu pluginy, ale jak wprowadzi się coś nowego, coś czego jeszcze nie ma to __może__, powtarzam __może__ będzie to hit.

**Comment by bartzzdev** [comment]
Dzięki ;)
@MrGregorix jakbyś chociaż jakoś uargumentował swoją wypowiedź raku łaku cebulaku :V
